#!/bin/bash
# system_info.sh - Display system information
echo "==================================="
echo " System Information Report"
echo "==================================="
echo ""

echo "Date and Time:"
echo " $(date)"
echo ""

echo "System:"
echo " Hostname: $(hostname)"
echo " OS: $(uname -s)"
echo " Kernel: $(uname -r)"
echo ""

echo "User:"
echo " Current user: $(whoami)"

echo " Home directory: $HOME"
echo " Shell: $SHELL"
echo ""

echo "System Load:"
echo " Uptime: $(uptime -p 2>/dev/null || uptime)"
echo ""

echo "Disk Usage:"
df -h / | awk 'NR==1 {print "  " $0} NR==2 {print "  " $0}'
echo ""

echo "Memory:"
free -h 2>/dev/null | awk 'NR==1 {print " " $0} NR==2 {print " " $0}' || echo " (memory info not available)"
echo ""

echo "==================================="
echo "Report generated by: $0"
echo "==================================="
